# Generated by Django 4.0.3 on 2022-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='наименование'),
        ),
    ]
